extends: airbnb
parser: babel-eslint
env:
  browser: true
  jest: true
globals:
  SyntheticEvent: true,
rules:
  react/prefer-stateless-function: off
  react/jsx-filename-extension: off
  react/jsx-one-expression-per-line: off
